export const COIN_LIST = {
    WS: [
        "KRW-BTC",
        "KRW-ETH",
        "KRW-XRP",
        "KRW-DOT",
        "KRW-ADA",
        "KRW-USDT",
        "KRW-AUCTION",
        "KRW-ZETA",
        "KRW-W",
        "KRW-ZRO",
        "KRW-LOOM",
        "KRW-LAYER",
        "KRW-BEAM",
        "KRW-SOL",
        "KRW-DOGE",
        "KRW-TRUMP",
        "KRW-MOCA",
        "KRW-SUI",
        "KRW-ANIME",
        "KRW-SONIC",
        "KRW-BIGTIME",
        "KRW-PEPE",
        "KRW-LINK",
        "KRW-BONK",
        "KRW-BLUR",
        "KRW-SEI",
        "KRW-TRX",
        "KRW-NEAR",
        "KRW-G",
      ],
    RENDER: {
        "KRW-BTC": "BITCOIN",
        "KRW-POT": "POLYCOIN",
        "KRW-ETH": "ETHEREUM",
        "KRW-XRP": "RIPPLE",
        "KRW-DOT": "POLCADOT",
        "KRW-ADA": "ADA",
        "KRW-USDT": "TETHER",
        "KRW-AUCTION": "BOUNCETOKEN",
        "KRW-ZETA": "ZETACHAIN",
        "KRW-W": "WORMHOLE",
        "KRW-ZRO": "LAYERZERO",
        "KRW-LOOM": "LOOM",
        "KRW-LAYER": "SOLLAYER",
        "KRW-BEAM": "BEAM",
        "KRW-SOL": "SOLANA",
        "KRW-DOGE": "DOGECOIN",
        "KRW-TRUMP": "TRUMP",
        "KRW-MOCA": "MOCA",
        "KRW-SUI": "SUI",
        "KRW-ANIME": "ANIMECOIN",
        "KRW-SONIC": "SONIC",
        "KRW-BIGTIME": "BIGTIME",
        "KRW-PEPE": "PEPE",
        "KRW-LINK": "CHAINLINK",
        "KRW-BONK": "BONK",
        "KRW-BLUR": "BLUR",
        "KRW-SEI": "SEI",
        "KRW-TRX": "TRON",
        "KRW-NEAR": "NEAR",
        "KRW-G": "GRAVITY",
      },
}